### ISSUE TITLE
Newly annotated genes in CN1

### ISSUE THREAD

**Issue by CodeCheong** [T2T-CN1/CN1#1]
Hi CN1 team,

Great work on the establishment of T2T-CN1! I have a question regarding the newly annotated genes as stated in the article. I could identify these genes in the Refseq annotation of CHM13. These genes were in the same chromosomes in both CN1 and CHM13, but with slightly different start and end positions. 

Can you explain what is meant by newly annotated genes here, and whether I have missed out on any other information about these genes that are different between the genomes?

**Comment by ChenGuangji** [comment]
> Hi CN1 team,
> 
> Great work on the establishment of T2T-CN1! I have a question regarding the newly annotated genes as stated in the article. I could identify these genes in the Refseq annotation of CHM13. These genes were in the same chromosomes in both CN1 and CHM13, but with slightly different start and end positions.
> 
> Can you explain what is meant by newly annotated genes here, and whether I have missed out on any other information about these genes that are different between the genomes?

Hi CodeCheong,

Thank you for your attention. Regarding your question, our answer is as follows:
1. These newly annotated genes in CN1 are newly from the genomic location information (based on the liftover with hg38/CHM13);
2. The name assignment of these newly annotated genes is based on the functional annotation;
3. These newly annotated genes are mostly copy number variations so that you would observe the different positions.

Hope these answers are helpful to you.

**Comment by CodeCheong** [comment]
Hi CN1 team,

Thanks for the reply! Also for the missing genes in CN1 but present in GRCh38, does this include genes that are either collapsed completely (eg. no orthologs at all) and also genes that do have similar sequence identity in CN1 but are now at a new genomic location? Thanks!

**Comment by ChenGuangji** [comment]
> Hi CN1 team,
> 
> Thanks for the reply! Also for the missing genes in CN1 but present in GRCh38, does this include genes that are either collapsed completely (eg. no orthologs at all) and also genes that do have similar sequence identity in CN1 but are now at a new genomic location? Thanks!

The missing genes in CN1 have no alignment relationship with GRCh38. And manually checking was focused on the upstream and downstream of the corresponding genome location to determine the loss of these genes.

**Comment by CodeCheong** [comment]
Thanks for the help. Also a side question, when using the CN1 gtf file "CN1_v0.8_Annotation_v202306.gtf", is there a way to identify the biotype of the gene (eg. protein coding, pseudogene, miRNA etc)?

**Comment by ChenGuangji** [comment]
> Thanks for the help. Also a side question, when using the CN1 gtf file "CN1_v0.8_Annotation_v202306.gtf", is there a way to identify the biotype of the gene (eg. protein coding, pseudogene, miRNA etc)?

It could be accomplished by finding the biotype of the corresponding gene in the GFF3 format with the label(gene_biotype).
